gekko:
  restart: always
  build: ./
  volumes:
    - ./volumes/gekko/history:/usr/src/app/history
    - ./config.js:/usr/src/app/config.js
  links:
    - redis
  environment:
   - HOST
   - PORT
  ports: # you can comment this out when using the nginx frontend
    - "${PORT}:${PORT}"

redis:
  image: redis:latest
  volumes:
    - ./volumes/redis:/data

## optionally uncomment if you wish to use nginx as a frontend
#nginx:
#  restart: always
#  image: jwilder/nginx-proxy
#  ports:
#    - "80:80"
#  volumes:
#    - /var/run/docker.sock:/tmp/docker.sock:ro
